In [1]:
import pandas as pd
import tensorflow as tf

tf.config.list_physical_devices('GPU')

physical_devices = tf.config.list_physical_devices('GPU')
try:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
except:
    pass

In [2]:

df= pd.read_csv("/Users/samriddhikumari/Desktop/College/symb/SEM_4/SML_prj/output/frame_features.csv")

columns_to_drop = ['lbp_10', 'lbp_11', 'lbp_12', 'lbp_13', 'lbp_14', 'lbp_15', 'lbp_16', 'lbp_17', 'lbp_18', 'lbp_19', 'lbp_20', 'lbp_21', 'lbp_22', 'lbp_23', 'lbp_24', 'lbp_25', 'lbp_26', 'lbp_27', 'lbp_28', 'lbp_29', 'lbp_30', 'lbp_31', 'lbp_32', 'lbp_33', 'lbp_34', 'lbp_35', 'lbp_36', 'lbp_37', 'lbp_38', 'lbp_39', 'lbp_40', 'lbp_41', 'lbp_42', 'lbp_43', 'lbp_44', 'lbp_45', 'lbp_46', 'lbp_47', 'lbp_48', 'lbp_49', 'lbp_50', 'lbp_51', 'lbp_52', 'lbp_53', 'lbp_54', 'lbp_55', 'lbp_56', 'lbp_57', 'lbp_58']

df.drop(columns=columns_to_drop, inplace=True)

# Assuming df is your original DataFrame
df_without_missing_values = df.dropna()

df= df_without_missing_values

df.columns

Index(['frames', 'lbp_0', 'lbp_1', 'lbp_2', 'lbp_3', 'lbp_4', 'lbp_5', 'lbp_6',
       'lbp_7', 'lbp_8', 'lbp_9', 'optical_flow_0', 'optical_flow_1',
       'optical_flow_2', 'optical_flow_3', 'Lip_Feature_1', 'Lip_Feature_2',
       'Lip_Feature_3', 'Lip_Feature_4', 'Lip_Feature_5', 'Lip_Feature_6',
       'Lip_Feature_7', 'Lip_Feature_8', 'Lip_Feature_9', 'Lip_Feature_10',
       'labels', 'person'],
      dtype='object')

In [8]:
selected_columns = df[['optical_flow_0', 'optical_flow_1', 'optical_flow_2', 'optical_flow_3']]

# Display the selected columns
selected_columns

      optical_flow_0  optical_flow_1  optical_flow_2  optical_flow_3
0           0.000312        0.000805        3.678836        1.905480
1           0.000977        0.002824        3.706850        1.886269
2           0.000247        0.000547        3.503586        1.801576
3           0.000202        0.000403        3.840143        1.642348
4           0.000217        0.000543        3.671226        1.678150
...              ...             ...             ...             ...
7565        0.000641        0.001318        3.417314        1.580235
7566        0.000618        0.001002        3.313716        1.629621
7567        0.000658        0.001157        3.489812        1.683946
7568        0.000607        0.000974        3.342736        1.850236
7569        0.000569        0.001060        3.418352        1.470691

[7567 rows x 4 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the labels
y_encoded = label_encoder.fit_transform(df['labels'])

# Check the mapping of original labels to encoded labels
label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Label Mapping:", label_mapping)

# Replace the original labels with encoded labels in the DataFrame
df['labels2'] = y_encoded

Label Mapping: {'आवश्यकता': 0, 'आसमान': 1, 'उड़': 2, 'उतर': 3, 'ऊंची': 4, 'एक': 5, 'कप': 6, 'कर': 7, 'करते': 8, 'करने': 9, 'करें': 10, 'का': 11, 'कागज़': 12, 'काट': 13, 'काले': 14, 'किलोमीटर': 15, 'की': 16, 'के': 17, 'केले': 18, 'कॉफी': 19, 'को': 20, 'क्या': 21, 'खा': 22, 'खाने': 23, 'खिल': 24, 'गया': 25, 'गलती': 26, 'गुलाबी': 27, 'गौर': 28, 'चलते': 29, 'चलें': 30, 'चाय': 31, 'चार': 32, 'चावल': 33, 'जल्दी': 34, 'जाएगा': 35, 'जूतों': 36, 'जोर': 37, 'टमाटर': 38, 'टुकड़ों': 39, 'टैक्सी': 40, 'ठंडा': 41, 'डांटेंगी': 42, 'डालने': 43, 'तक': 44, 'तीन': 45, 'तेज': 46, 'तो': 47, 'दुपट्टा': 48, 'देखो': 49, 'देना': 50, 'दो': 51, 'धीरे': 52, 'धोलो': 53, 'न': 54, 'नहीं': 55, 'नारंगी': 56, 'नीले': 57, 'नौ': 58, 'पका': 59, 'पतंग': 60, 'पर': 61, 'पहनो': 62, 'पांच': 63, 'पानी': 64, 'पार': 65, 'पार्क': 66, 'पियें': 67, 'पीकर': 68, 'पीली': 69, 'पौधों': 70, 'प्याज': 71, 'फल': 72, 'फिर': 73, 'फूल': 74, 'फोन': 75, 'बच्चे': 76, 'बनाओ': 77, 'बर्तन': 78, 'बस': 79, 'बात': 80, 'बाद': 81, 'बार': 82, 'बारीक': 83, 'बैग': 84, 'ब्रश': 85, 'भर': 86, 'मत': 87, 'माँ': 88, 'मिनट': 89, 'मिर्च': 90, 'मिलाएं': 91, 'में': 92, 'मेरे': 93, 'यह': 94, 'यात्री': 95, 'रंग': 96, 'रखें': 97, 'रसोई': 98, 'रही': 99, 'रहे': 100, 'रास्ता': 101, 'रिंग': 102, 'लाल': 103, 'लिए': 104, 'लीटर': 105, 'लें': 106, 'लो': 107, 'शर्ट': 108, 'सफ़ेद': 109, 'सब्जियां': 110, 'साथ': 111, 'साफ': 112, 'सारे': 113, 'सावधानी': 114, 'से': 115, 'सेब': 116, 'स्कूल': 117, 'हरा': 118, 'हरी': 119, 'हरे': 120, 'हुआ': 121, 'हैं': 122, 'हो': 123}

In [12]:
df

,frames,lbp_0,lbp_1,lbp_2,lbp_3,lbp_4,lbp_5,lbp_6,lbp_7,lbp_8,...,Lip_Feature_4,Lip_Feature_5,Lip_Feature_6,Lip_Feature_7,Lip_Feature_8,Lip_Feature_9,Lip_Feature_10,labels,person,labels2
0,0001.jpg,218,330,275,583,873,751,516,431,437,...,109.018347,43.104524,62.201286,62.072538,63.007936,43.046487,133.003759,जल्दी,agni,34
1,0002.jpg,218,330,275,583,873,751,516,431,437,...,103.004854,45.044423,66.121101,65.030762,66.000000,45.011110,127.003937,जल्दी,agni,34
2,0003.jpg,218,330,275,583,873,751,516,431,437,...,105.004762,45.044423,67.119297,66.030296,66.007575,44.011362,128.015624,जल्दी,agni,34
3,0004.jpg,218,330,275,583,873,751,516,431,437,...,110.018180,43.046487,61.073726,60.033324,61.000000,43.011626,132.034087,जल्दी,agni,34
4,0005.jpg,218,330,275,583,873,751,516,431,437,...,113.004425,43.046487,61.073726,60.008333,60.000000,42.011903,134.003731,जल्दी,agni,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7565,7662.jpg,161,238,227,725,1430,975,332,243,256,...,164.878743,58.051701,88.119237,81.498466,85.287748,57.078893,197.732142,करें,yasaswini,10
7566,7663.jpg,161,238,227,725,1430,975,332,243,256,...,168.961534,58.694122,88.119237,82.607506,86.284413,59.076222,203.887224,करें,yasaswini,10
7567,7664.jpg,161,238,227,725,1430,975,332,243,256,...,172.742583,56.718604,85.988371,80.504658,86.209048,58.034473,204.882893,करें,yasaswini,10
7568,7665.jpg,161,238,227,725,1430,975,332,243,256,...,171.842952,57.706152,86.977008,80.399005,85.146932,56.035703,204.882893,करें,yasaswini,10
7569,7666.jpg,161,238,227,725,1430,975,332,243,256,...,174.928557,58.051701,87.965902,80.504658,86.209048,58.077534,208.062491,करें,yasaswini,10

In [13]:

# Assuming df is your DataFrame containing lip features and labels
# Splitting the data into features and labels
from sklearn.model_selection import train_test_split
X = df.drop(columns=['frames', 'labels','person','labels2'])  # Assuming 'frames' is not a feature
y = df['labels']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [14]:

import pandas as pd

from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score


# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform the training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform the testing data
X_test_scaled = scaler.transform(X_test)

# XGBoost

In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

# Initialize XGBoost classifier
xgb_classifier = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3)

# Train the classifier
xgb_classifier.fit(X_train_scaled, y_train)

# Make predictions
y_pred = xgb_classifier.predict(X_test_scaled)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.23469837076177896

# CatBoost

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score

# Initializing CatBoost classifier
catboost_classifier = CatBoostClassifier(iterations=100, learning_rate=0.1, depth=6)

catboost_classifier.fit(X_train_scaled, y_train, verbose=100)

# Making predictions
catboost_preds = catboost_classifier.predict(X_test_scaled)

# Evaluating the classifier
catboost_accuracy = accuracy_score(y_test, catboost_preds)

print("CatBoost Accuracy:", catboost_accuracy)

0:	learn: 4.7291286	total: 161ms	remaining: 15.9s
99:	learn: 2.4017949	total: 6.17s	remaining: 0us
CatBoost Accuracy: 0.2311756935270806

# Light Boost

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import lightgbm as lgb
from sklearn.metrics import accuracy_score

# Create dataset for LightGBM
train_data = lgb.Dataset(X_train_scaled, label=y_train)
test_data = lgb.Dataset(X_test_scaled, label=y_test)

# Set parameters for LightGBM
params = {
    'objective': 'multiclass',  # Multiclass classification
    'num_class': len(set(y_train)),  # Number of classes
}

# Train LightGBM model
num_round = 100  # Number of boosting rounds
lgb_model = lgb.train(params, train_data, num_round)

# Predictions
y_pred = lgb_model.predict(X_test_scaled)
y_pred_class = [int(x.argmax()) for x in y_pred]

# Accuracy
accuracy = accuracy_score(y_test, y_pred_class)
print("Accuracy:", accuracy)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import lightgbm as lgb
from sklearn.metrics import accuracy_score

# Assuming X_train_scaled, X_test_scaled, y_train, y_test are already defined

# Create dataset for LightGBM
train_data = lgb.Dataset(X_train_scaled, label=y_train)
test_data = lgb.Dataset(X_test_scaled, label=y_test)

# Set parameters for LightGBM
params = {
    'objective': 'multiclass',  # Multiclass classification
    'num_class': len(set(y_train)),  # Number of classes
    'metric': 'multi_logloss',  # Metric for evaluation
    'boosting_type': 'gbdt',  # Gradient Boosting Decision Tree
    'num_leaves': 31,  # Maximum number of leaves in one tree
    'learning_rate': 0.05,  # Learning rate
    'feature_fraction': 0.9,  # Feature fraction
    'bagging_fraction': 0.8,  # Bagging fraction
    'bagging_freq': 5,  # Frequency for bagging
    'verbose': 0  # Verbose output
}

# Train LightGBM model
num_round = 100  # Number of boosting rounds
lgb_model = lgb.train(params, train_data, num_round, valid_sets=[test_data], early_stopping_rounds=10)

# Predictions
y_pred = lgb_model.predict(X_test_scaled, num_iteration=lgb_model.best_iteration)
y_pred_class = [int(x.argmax()) for x in y_pred]

# Accuracy
accuracy = accuracy_score(y_test, y_pred_class)
print("Accuracy:", accuracy)